version: "3.6"

services:
 postgres:
  image: postgres:14.3
  restart: always
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "postgres:/var/lib/postgresql/data"

 bx:
  image: blockexchange/blockexchange
  depends_on:
   - postgres
  environment:
   - PGUSER=postgres
   - PGPASSWORD=enter
   - PGHOST=postgres
   - PGDATABASE=postgres
   - PGPORT=5432
   - LOGLEVEL=debug
   - BLOCKEXCHANGE_NAME=My-Blockexchange
   - BLOCKEXCHANGE_OWNER=yourname
   - BLOCKEXCHANGE_KEY=abcdefSecretKey
   - BLOCKEXCHANGE_COOKIE_PATH=/
   - BLOCKEXCHANGE_COOKIE_DOMAIN=localhost
   - BLOCKEXCHANGE_COOKIE_SECURE=false
   - BLOCKEXCHANGE_TEST_DATA=true
   - BASE_URL=http://localhost:8080
  ports:
   - "8080:8080"

 sut:
  depends_on:
   - bx
  build:
   context: ./test
   args:
    ENGINE_VERSION: ${ENGINE_VERSION:-5.7.0}
  user: root
  volumes:
    - "./:/root/.minetest/worlds/world/worldmods/blockexchange/"
    - "world_data:/root/.minetest/worlds/world"
    - "./test/world.mt:/root/.minetest/worlds/world/world.mt"
    - "./test/minetest.conf:/minetest.conf"
    - "./coverage:/var/lib/minetest"

volumes:
  world_data: {}
  postgres: {}