mtt.register("blockexchange.get_base_pos, returns proper positive coordinates", function(callback)
	local pos = blockexchange.get_base_pos({x=0, y=0, z=0}, {x=5, y=1, z=0})
	assert(pos)
	assert(0 == pos.x)
	assert(0 == pos.y)
	assert(0 == pos.z)

	pos = blockexchange.get_base_pos({x=0, y=0, z=0}, {x=5, y=16, z=0})
	assert(pos)
	assert(0 == pos.x)
	assert(16 == pos.y)
	assert(0 == pos.z)

	callback()
end)

mtt.register("blockexchange.get_base_pos, returns proper negative coordinates", function(callback)
	local pos = blockexchange.get_base_pos({x=0, y=0, z=0}, {x=-5, y=0, z=0})
	assert(pos)
	assert(-16 == pos.x)
	assert(0 == pos.y)
	assert(0 == pos.z)

	pos = blockexchange.get_base_pos({x=0, y=0, z=0}, {x=-5, y=-17, z=0})
	assert(pos)
	assert(-16 == pos.x)
	assert(-32 == pos.y)
	assert(0 == pos.z)
	callback()
end)
