name: coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - name: test
      run: |
        docker-compose up --exit-code-from sut
        sudo sed -i 's#/root/.minetest/worlds/world/worldmods/blockexchange/##g' coverage/lcov.info
    - name: Coveralls
      uses: coverallsapp/github-action@v2