name: integration-test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v1

    - name: integration-test
      run: ./test/integration-test-standalone.sh
